//////////
// CORE //
//////////
export const RESET_STATE = 'RESET_STATE'

/////////////
// GENERAL //
/////////////
export const WATCH_SCROLL_EVENT = 'WATCH_SCROLL_EVENT'

////////////
// DIALOG //
////////////
export const IS_DIALOG_SHOW = 'IS_DIALOG_SHOW'

///////////
// TOAST //
///////////
export const IS_DEFAULT_TOAST_SHOW_LEFT = 'IS_DEFAULT_TOAST_SHOW_LEFT'
export const IS_DEFAULT_TOAST_SHOW_RIGHT = 'IS_DEFAULT_TOAST_SHOW_RIGHT'
export const IS_DEFAULT_TOAST_SHOW_CENTER = 'IS_DEFAULT_TOAST_SHOW_CENTER'
export const IS_DEFAULT_TOAST_SHOW_SUCCESS = 'IS_DEFAULT_TOAST_SHOW_SUCCESS'
export const IS_DEFAULT_TOAST_SHOW_DANGER = 'IS_DEFAULT_TOAST_SHOW_DANGER'
export const IS_DEFAULT_TOAST_SHOW_WARNING = 'IS_DEFAULT_TOAST_SHOW_WARNING'
export const IS_ACTION_TOAST_SHOW = 'IS_ACTION_TOAST_SHOW'
export const IS_ACTION_AFTER_TOAST_SHOW = 'IS_ACTION_AFTER_TOAST_SHOW'
export const IS_ACTIONS_TOAST_SHOW = 'IS_ACTIONS_TOAST_SHOW'
export const IS_ACTIONS_AFTER_TOAST_SHOW = 'IS_ACTIONS_AFTER_TOAST_SHOW'
export const ACTION_TOAST_$T = 'ACTION_TOAST_$T'
export const ACTIONS_TOAST_$T = 'ACTIONS_TOAST_$T'