//////////
// CORE //
//////////
export const RESET_STATE = 'RESET_STATE'

/////////////
// GENERAL //
/////////////
export const WATCH_SCROLL_EVENT = 'WATCH_SCROLL_EVENT'

////////////
// DIALOG //
////////////
export const IS_DIALOG_SHOW = 'IS_DIALOG_SHOW'

///////////
// TOAST //
///////////
export const IS_DEFAULT_TOAST_SHOW_LEFT = 'IS_DEFAULT_TOAST_SHOW_LEFT'
export const IS_DEFAULT_TOAST_SHOW_RIGHT = 'IS_DEFAULT_TOAST_SHOW_RIGHT'
export const IS_DEFAULT_TOAST_SHOW_CENTER = 'IS_DEFAULT_TOAST_SHOW_CENTER'
export const IS_DEFAULT_TOAST_SHOW_SUCCESS = 'IS_DEFAULT_TOAST_SHOW_SUCCESS'
export const IS_DEFAULT_TOAST_SHOW_DANGER = 'IS_DEFAULT_TOAST_SHOW_DANGER'
export const IS_DEFAULT_TOAST_SHOW_WARNING = 'IS_DEFAULT_TOAST_SHOW_WARNING'
export const IS_ACTION_TOAST_SHOW = 'IS_ACTION_TOAST_SHOW'
export const IS_ACTION_AFTER_TOAST_SHOW = 'IS_ACTION_AFTER_TOAST_SHOW'
export const IS_ACTIONS_TOAST_SHOW = 'IS_ACTIONS_TOAST_SHOW'
export const IS_ACTIONS_AFTER_TOAST_SHOW = 'IS_ACTIONS_AFTER_TOAST_SHOW'
export const ACTION_TOAST_$T = 'ACTION_TOAST_$T'
export const ACTIONS_TOAST_$T = 'ACTIONS_TOAST_$T'

////////////////
// DATEPICKER //
////////////////
export const IS_DATE_PICKER_MODAL_SHOW = 'IS_DATE_PICKER_MODAL_SHOW'
export const IS_RANGE_DATE_PICKER_MODAL_SHOW = 'IS_RANGE_DATE_PICKER_MODAL_SHOW'
export const DATE_PICKER_EVENT_POINT = 'DATE_PICKER_EVENT_POINT'
export const DATE_PICKER_SELECTED_DATE = 'DATE_PICKER_SELECTED_DATE'
export const RANGE_DATE_PICKER_EVENT_POINT = 'RANGE_DATE_PICKER_EVENT_POINT'
export const RANGE_DATE_PICKER_SELECTED_DATE = 'RANGE_DATE_PICKER_SELECTED_DATE'
export const RANGE_DATE_PICKER_SELECTED_START_DATE = 'RANGE_DATE_PICKER_SELECTED_START_DATE'
export const RANGE_DATE_PICKER_SELECTED_END_DATE = 'RANGE_DATE_PICKER_SELECTED_END_DATE'

////////////
// SEARCH //
////////////
export const IS_SEARCH_ACTIVE = 'IS_SEARCH_ACTIVE'
export const GET_SEARCH_DATA = 'GET_SEARCH_DATA'

//////////
// ICON //
//////////
export const GET_ICON_DATA = 'GET_ICON_DATA'

///////////////
// ANIMAITON //
///////////////
export const UPDATE_MAIN_ANI_STATUS_DATA = 'UPDATE_MAIN_ANI_STATUS_DATA'

///////////
// MODAL //
///////////
export const ADVANCED_MODAL_DETAIL_PAGE_SHOW_HIDE = 'ADVANCED_MODAL_DETAIL_PAGE_SHOW_HIDE'
export const SHOW_ADVANCED_MODAL = 'SHOW_ADVANCED_MODAL'